name: GLK PR Workflow (repro)

on:
  workflow_call:

jobs:
  glk:
    runs-on: ubuntu-latest
    steps:
    - name: Commit and push changes
      run: |
        echo "whoami:"
        whoami
        echo "rendered-and-executed-line:"
        echo "would-push-to:HEAD:${{ github.event.pull_request.head.ref || github.ref_name }}"
